### ISSUE TITLE
大哥缺了几个cpp编译不了

### ISSUE THREAD

**Issue by emako** [DragonPang/QtPlayer#1]

**Comment by DragonPang** [comment]
编译应该是没有问题的，你缺什么文件？

**Comment by JL-Dawson** [comment]
你好，我下载之后编译报错：videodecoder.cpp不存在

**Comment by DragonPang** [comment]
这个问题应该是videodecoder.cpp后面改名成为devoder.cpp了，.pro文件中没有删除掉，你把.pro中的videodecoder.cpp删除掉即可。
